language: csharp
solution: Solutions/ClassLibrary1.sln

install:
  - nuget restore Solutions/ClassLibrary1.sln
  - nuget install NUnit.ConsoleRunner -ExcludeVersion  -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Solutions/ClassLibrary1.sln
  - mono ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe Tests/Unit/ClassLibrary1UnitTests/bin/Release/ClassLibrary1UnitTests.dll